### ISSUE TITLE
Parameter url must be a string

### ISSUE THREAD

**Issue by brianyoungblood** [gsingers/slack-webex-plugin#2]
I seem to see this error on my server centos and node v7.4.0. (locally on os x works fine) and not sure what the differences are, or reason for the error. Any help would be great. Thanks. brian

node config.js
url.js:95
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:95:11)
    at Object.urlParse [as parse] (url.js:89:5)
    at WebSocket.initAsClient (/opt/slack-webex-plugin/node_modules/node-slackbot/node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (/opt/slack-webex-plugin/node_modules/node-slackbot/node_modules/ws/lib/WebSocket.js:74:18)
    at /opt/slack-webex-plugin/node_modules/node-slackbot/lib/slackbot.js:110:15
    at IncomingMessage.<anonymous> (/opt/slack-webex-plugin/node_modules/node-slackbot/lib/slackbot.js:52:18)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

**Comment by brianyoungblood** [comment]
Resolved this by making sure I had the correct slackbot key that starts with "xoxb-"

**Comment by merciero** [comment]
Can you elaborate how you fixed it? Where does this key need go and how did you know the correct one. Thanks
